name: "linux checks"

on:
  pull_request:
  push:
env:
  BUILD_TYPE: Release
  ALSOFT_DRIVERS: "null" # no op alsoft backend
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-ccache
        with:
          path: /var/cache/ccache
          key: ccache-${{ runner.os }}-${{ hashFiles('./flake.*', './default.nix') }}
          restore-keys: |
            ccache-

      - run: |
          sudo mkdir /var/cache/ccache
          sudo chown -R `whoami` /var/cache/ccache
          sudo chmod a+rwx /var/cache/ccache

      - uses: actions/cache@v3
        id: cache-nix
        with:
          path: ./nix-fs
          key: nix-${{ runner.os }}-${{ hashFiles('./flake.*', './default.nix') }}

      - if: ${{ steps.cache-nix.outputs.cache-hit != 'true' }}
        name: create filesystem in file
        run: mke2fs -t ext4 ./nix-fs 4,608M # 4.5 gib

      - name: mount nix-fs and
        run: |
          sudo mkdir /nix
          sudo mount -t ext4 ./nix-fs /nix
          sudo chown -R `whoami` /nix

      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "checks linux and pre commit"
        run: |
          nix flake check --print-build-logs --quiet

      - name: "build it"
        run: |
          nix build --print-build-logs --quiet  --option extra-sandbox-paths /var/cache/ccache

      - name: unmount nix-fs
        run: |
          sudo systemctl stop nix-daemon.socket
          sudo systemctl stop nix-daemon
          sudo du -sh /nix
          sudo chmod -R a+rwx /var/cache/ccache
          sudo du -sh /var/cache/ccache
          sudo umount /nix
