name: "Test"

on:
  pull_request:
  push:
env:
  BUILD_TYPE: Release
  ALSOFT_DRIVERS: "null" # no op alsoft backend
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: "checks linux and pre commit"
      run: nix flake check

