name: "linux checks"

on:
  pull_request:
  push:
env:
  BUILD_TYPE: Release
  ALSOFT_DRIVERS: "null" # no op alsoft backend
jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: "checks linux and pre commit"
        run: |
          nix flake check --print-build-logs --quiet

      - name: activate environment
        uses: HatsuneMiku3939/direnv-action@v1

      - name: "build it"
        run: |
          mkdir build
          cmake -B./build -S . -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1
          cmake --build ./build/

      - name: "set up gui environment"
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          # sudo apt install plasma-workspace
          # startplasma-x11 &
          sleep 1

      - name: "run tests"
        run: |
          cd build
          ctest --output-on-failure
