name: "linux checks"

on:
  pull_request:
  push:
env:
  BUILD_TYPE: Release
  ALSOFT_DRIVERS: "null" # no op alsoft backend
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache-nix
        with:
          path: ./nix-fs
          key: ${{ runner.os }}-${{ hashFiles('./flake.*', './default.nix') }}-nix

      - if: ${{ steps.cache-nix.outputs.cache-hit != 'true' }}
        name: create filesystem in file
        run: mke2fs -t ext4 ./nix-fs 10G # compressed when caching this is not a problem

      - name: mount nix-fs
        run: |
          sudo mkdir /nix
          sudo mount -t ext4 ./nix-fs /nix
          sudo chown -R `whoami` /nix

      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "checks linux and pre commit"
        run: |
          nix flake check --print-build-logs --quiet

      - name: "build it"
        run: |
          nix build --print-build-logs --quiet

      - name: unmount nix-fs
        run: |
          sudo systemctl stop nix-daemon.socket
          sudo systemctl stop nix-daemon
          sudo du -sh /nix
          sudo umount /nix
