name: "linux checks"

on:
  pull_request:
  push:
env:
  BUILD_TYPE: Release
  ALSOFT_DRIVERS: "null" # no op alsoft backend
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: "checks linux and pre commit"
        run: |
          nix flake check --print-build-logs --quiet

      - name: "build it"
        run: |
          nix build --print-build-logs --quiet
