name: "Test"

on:
  pull_request:
  push:
env:
  BUILD_TYPE: Release
  ALSOFT_DRIVERS: "null" # no op alsoft backend
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - run: |
        sudo mkdir -p /nix
        sudo chmod -R 777 /nix
    - uses: actions/cache/restore@v3
      id: nix-cache
      with:
        path: |
          # See https://github.com/actions/cache/pull/726
          /nix/store/**
          /nix/var/nix/*/*
          /nix/var/nix/db/*
          /nix/var/nix/db/*/**
          !/nix/var/nix/daemon-socket/socket
          !/nix/var/nix/userpool/*
          !/nix/var/nix/gc.lock
          !/nix/var/nix/db/big-lock
          !/nix/var/nix/db/reserved
        key: nix-store-${{ hashFiles('**/flake.*') }}
      
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: HatsuneMiku3939/direnv-action@v1

    - name: configure
      run : cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja

    # - name: build
    #   run : cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    #
    #
    # - name: test
    #   working-directory: ${{github.workspace}}/build
    #   run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

    - name: save cahce
      if: steps.nix-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with: # github doesn't support anchors why? 
        # FIXME: DRY this duplicate defination
        path: |
          # See https://github.com/actions/cache/pull/726
          /nix/store/**
          /nix/var/nix/*/*
          /nix/var/nix/db/*
          /nix/var/nix/db/*/**
          !/nix/var/nix/daemon-socket/socket
          !/nix/var/nix/userpool/*
          !/nix/var/nix/gc.lock
          !/nix/var/nix/db/big-lock
          !/nix/var/nix/db/reserved
        key: nix-store-${{ hashFiles('**/flake.*') }}

